stacks: ./data/stacks
templates: ./data/templates
terraform_commands: ./data/scripts
stack_volume: not_defined

terraform_image: jetbrainsinfra/terraform

expire_day: 5
notify_day: 4

frontend_address: http://127.0.0.1:3000
backend_address: http://127.0.0.1:8080


security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: 759913667428-fnjj8ofelfk9asa0lnoadrnqun5l5veo.apps.googleusercontent.com
      clientSecret: ZwLBr4iqlscXdfD7hFK7_-Dy
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
      scope:
        - openid
        - email
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    username: ${EMAIL_LOGIN}
    password: ${EMAIL_PASSWORD}
  resources:
    static-locations: file:src/main/javascript/,classpath:/static/
    cache-period: 0
